### ISSUE TITLE
Saving files fails if path contains a space

### ISSUE THREAD

**Issue by 0xMrNight** [CorpseCoder/ADB#1]
Host OS: Windows

![image](https://github.com/CorpseCoder/ADB/assets/64628456/83bdbf67-b25c-4ec1-a9ae-792709815738)

Error seems to originate from [line #23](https://github.com/CorpseCoder/ADB/blob/f1ad844622158cae2973734bd6d1c996aaa7b1d3/Windows.py#L23)

**Comment by CorpseCoder** [comment]
Please go change your (user)name

**Comment by 0xMrNight** [comment]
By the way, congrats for breaking your code _further_!

![image](https://github.com/CorpseCoder/ADB/assets/64628456/68e145c8-1280-4751-b92d-b3c81b58adf1)

**Comment by CorpseCoder** [comment]
Will re-base the whole app from scratch tomorrow with macOS support...

**Comment by 0xMrNight** [comment]
Works now 👍
